version: 2
updates:
    - package-ecosystem: 'npm'
      directories:
          - '/'
          - '/apps/frontend'
          - '/apps/backend'
      schedule:
          interval: 'weekly'
          day: 'friday'
          time: '08:00'
      rebase-strategy: 'auto'
      open-pull-requests-limit: 1
      allow:
          - dependency-type: 'all'
            update-types:
                - 'semver-minor'
                - 'semver-patch'
      milestone: 'D11 - Operations and maintenance'
      labels:
          - 'dependencies'
      automerged_updates:
          - match:
                update_type: 'semver-patch'
