version: 2
updates:
    - package-ecosystem: 'npm'
      directories:
          - '/'
          - '/apps/frontend'
          - '/apps/backend'
      schedule:
          interval: 'weekly'
          day: 'friday'
          time: '08:00'
          timezone: 'Europe/Zurich'
      rebase-strategy: 'auto'
      open-pull-requests-limit: 1
      reviewers:
          - 'danieljancar'
      labels:
          - 'dependencies'
      milestone: 2
      ignore:
          - dependency-name: '*'
            update-types:
                - 'version-update:semver-major'
                - 'version-update:semver-minor'
      groups:
          patch-updates:
              patterns:
                  - '*'
              update-types:
                  - 'patch'
