## PR Labeler Configuration

pr:
    - '**/*'

ci/cd:
    - .github/workflows/**

husky:
    - .husky/**

assets:
    - assets/**

docs:
    - docs/**
    - README.md
    - CONTRIBUTING.md

scripts:
    - scripts/**

bruno:
    - bruno/**

# /apps/*
frontend:
    - apps/frontend/**

backend:
    - apps/backend/**
