name: Deploy development (Backend & Frontend)

on:
    push:
        branches: [develop]
        paths:
            - 'apps/backend/**'
            - 'apps/frontend/**'
    workflow_dispatch:

jobs:
    determine_changes:
        runs-on: ubuntu-latest
        outputs:
            backend_changed: ${{ steps.check_backend.outputs.changed }}
            frontend_changed: ${{ steps.check_frontend.outputs.changed }}
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3
              with:
                  fetch-depth: 2

            - name: Check if Backend files changed
              id: check_backend
              run: |
                  if git diff --name-only HEAD^ HEAD | grep '^apps/backend/'; then
                    echo "changed=true" >> $GITHUB_OUTPUT
                  else
                    echo "changed=false" >> $GITHUB_OUTPUT
                  fi

            - name: Check if Frontend files changed
              id: check_frontend
              run: |
                  if git diff --name-only HEAD^ HEAD | grep '^apps/frontend/'; then
                    echo "changed=true" >> $GITHUB_OUTPUT
                  else
                    echo "changed=false" >> $GITHUB_OUTPUT
                  fi

    deploy_backend:
        needs: determine_changes
        if: needs.determine_changes.outputs.backend_changed == 'true'
        uses: ./.github/workflows/dev-deployment-common.yml
        with:
            app_path: 'apps/backend/'
            docker_image_name: 'hangbuddies/backend:dev'

    deploy_frontend:
        needs: determine_changes
        if: needs.determine_changes.outputs.frontend_changed == 'true'
        uses: ./.github/workflows/dev-deployment-common.yml
        with:
            app_path: 'apps/frontend/'
            docker_image_name: 'hangbuddies/frontend:dev'
