name: Deploy development (Backend & Frontend)

on:
    push:
        branches: [develop]
        paths:
            - 'apps/backend/**'
            - 'apps/frontend/**'
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3
              with:
                  fetch-depth: 2

            - name: Check if Backend files changed
              id: check_backend
              run: |
                  if git diff --name-only HEAD^ HEAD | grep '^apps/backend/'; then
                    echo "backend_changed=true" >> $GITHUB_OUTPUT
                  else
                    echo "backend_changed=false" >> $GITHUB_OUTPUT
                  fi

            - name: Check if Frontend files changed
              id: check_frontend
              run: |
                  if git diff --name-only HEAD^ HEAD | grep '^apps/frontend/'; then
                    echo "frontend_changed=true" >> $GITHUB_OUTPUT
                  else
                    echo "frontend_changed=false" >> $GITHUB_OUTPUT
                  fi

            - name: Set up SSH Agent and Key
              uses: webfactory/ssh-agent@v0.8.0
              with:
                  ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

            - name: Set up WireGuard
              uses: egor-tensin/setup-wireguard@v1
              with:
                  endpoint: '${{ secrets.WG_ENDPOINT }}'
                  endpoint_public_key: '${{ secrets.WG_ENDPOINT_PUBLIC }}'
                  ips: '${{ secrets.WG_IPS }}'
                  allowed_ips: '${{ secrets.WG_ALLOWED_IPS }}'
                  private_key: '${{ secrets.WG_PRIVATE }}'

            - name: Add Server's Host Key to known_hosts
              run: ssh-keyscan -H ${{ secrets.SERVER_HOST_NAME }} >> ~/.ssh/known_hosts

            - name: Create SSH Config File
              run: |
                  mkdir -p ~/.ssh
                  cat <<EOF > ~/.ssh/config
                  Host server
                    HostName ${{ secrets.SERVER_HOST_NAME }}
                    User ${{ secrets.SERVER_USER }}
                    IdentityFile ~/.ssh/id_rsa
                  EOF
                  chmod 600 ~/.ssh/config

            - name: Deploy Backend (if changed)
              if: steps.check_backend.outputs.backend_changed == 'true'
              run: |
                  echo "Deploying Backend..."
                  ssh server << EOF
                    cd ${{ secrets.DEV_DEPLOYMENT_DIR }}
                    git pull
                    rm devops/.env
                    echo "${{ secrets.DEPLOYMENT_ENV }}" > devops/.env
                    echo "Created .env file on server from repository secret"
                    docker build -t hangbuddies/frontend:dev -f apps/frontend/dev-dockerfile --no-cache apps/frontend/
                    cd devops
                    docker-compose down
                    docker-compose up -d
                  EOF

            - name: Deploy Frontend (if changed)
              if: steps.check_frontend.outputs.frontend_changed == 'true'
              run: |
                  echo "Deploying Frontend..."
                  ssh server << EOF
                    cd ${{ secrets.DEV_DEPLOYMENT_DIR }}
                    git pull
                    rm devops/.env
                    echo "${{ secrets.DEPLOYMENT_ENV }}" > devops/.env
                    echo "Created .env file on server from repository secret"
                    docker build -t hangbuddies/frontend:dev apps/frontend/ --no-cache
                    cd devops
                    docker-compose down
                    docker-compose up -d
                  EOF
